Added error handling for Spring Boot 2
bliblidotcom/common-plugin pull request #7
Opened 2019-07-01 07:19 UTC by bertzzie

Should we increase version number?

@khannedy @andirdju

2019-07-02 05:30 UTC, khannedy commented
@bertzzie yeah, we need to change this version to 2.0.0, so every one know, this is for spring boot 2

2019-07-02 05:31 UTC, khannedy requested changes
upgrade version to 2.0.0-SNAPSHOT

2019-07-08 00:37 UTC, bertzzie commented
Updated @khannedy

2019-08-07 11:26 UTC, khannedy approved these changes

2019-08-07 11:26 UTC, merged